version: '3'
services:

  rabbit:
    image: rabbitmq:3-alpine
    hostname: 
      exclusible-rabbit
    ports:
      - 5671:5672
    networks:
      - exclusible-net

  postgres:
    image: postgres:11-alpine
    # volumes:
    #   - docker-data/postgres:/var/lib/postgresql/data postgres:11-alpine
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=exclusible 
      - POSTGRES_PASSWORD=123       
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=exclusible
    networks:
      - exclusible-net

networks:
    exclusible-net:
  # config-service:
  #   build: 
  #     context: .
  #     dockerfile: apps/config-service/Dockerfile      
  #   depends_on:
  #     - rabbit
  #     - postgres
  #   networks:
  #     - exclusible-net
  #   environment:
  #     - RABBIT_URL=amqp://guest:guest@rabbit:5672
  #     - RABBIT_IS_DURABLE=0
  #     - RABBIT_CONFIG_QUEUE=config_queue
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_PORT=5431
  #     - POSTGRES_USERNAME=exclusible
  #     - POSTGRES_PASSWORD=123
  #     - POSTGRES_DATABASE=exclusible

  # exchange-api:
  #   build: 
  #     context: .
  #     dockerfile: apps/exchange-api/Dockerfile      
  #   depends_on:
  #     - rabbit      
  #     - config-service
  #   ports:
  #     - 3333:3333
  #   networks:
  #     - exclusible-net
  #   environment:
  #     - PORT=3333
  #     - RABBIT_URL=amqp://guest:guest@rabbit:5672
  #     - RABBIT_IS_DURABLE=0
  #     - RABBIT_CONFIG_QUEUE=config_queue
  #     - AUTH0_ISSUER_URL=https://baio.eu.auth0.com/
  #     - KRAKEN_WS_URL=wss://ws.kraken.com/
  #     - KRAKEN_FAILURE_RETRY_DELAY=3000

  # client-app:
  #   build: 
  #     context: .
  #     dockerfile: apps/client-app/Dockerfile      
  #   # depends_on:
  #   #   - exchange-api
  #   ports:
  #     - 4200:80
  #   networks:
  #     - exclusible-net
  #   environment:
  #     - NEXT_PUBLIC_BASE_URL=localhost:3333
  #     - NEXT_PUBLIC_WS_URL=ws://localhost:3333
  #     - NEXT_PUBLIC_AUTH0_DOMAIN=baio.eu.auth0.com
  #     - NEXT_PUBLIC_AUTH0_CLIENT_ID=5Thid6uCDtF5E1jmWb5zxQkjoO3HiQX4
  #     - NEXT_PUBLIC_AUTH0_REDIRECT_URL=http://localhost:4200

