@host = http://localhost:3333

### 
Post {{host}}/config/spread
Content-Type: application/json 
Accept: application/json

{
  "buyOffset": -500,
  "sellOffset": 1000
}


### 
GET {{host}}/config/spread