export const CONFIG_SERVICE_NAME = 'CONFIG_SERVICE_NAME';
export const CONFIG_SERVICE_PROXY = 'CONFIG_SERVICE_PROXY';
export const CONFIG_SERVICE_SET_SPREAD_PATTERN_NAME = 'CONFIG_SERVICE_SET_SPREAD_PATTERN_NAME';
export const CONFIG_SERVICE_GET_SPREAD_PATTERN_NAME = 'CONFIG_SERVICE_GET_SPREAD_PATTERN_NAME';